version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  maven: circleci/maven@0.0.9
workflows:
  build-deploy:
    jobs:
      - build:
          branches:
            only:
              - master
              # - dev
              - qa      
      - aws-ecr/build-and-push-image:
          repo: ${CIRCLE_PROJECT_REPONAME}
          region: AWS_REGION_ENV_VAR_NAME
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          tag: ${CIRCLE_BUILD_NUM}
          create-repo: true 
          attach-workspace: true
          requires:
            - build
          branches:
            only:
              - master
              # - dev
              - qa             
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mvn clean install
      - persist_to_workspace:
          root: .
          paths:
            - target/dependency/BOOT-INF/lib
            - target/dependency/META-INF
            - target/dependency/BOOT-INF/classes
